FROM node:16

# Install build tools
RUN apt-get update && \
    apt-get install -y build-essential python3

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json first
COPY package*.json ./

# Install app dependencies (this will rebuild bcrypt)
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port that the app will run on
EXPOSE 5003

# Run the application when the container starts
CMD ["npm", "start"]
