name: EC2 File Creation

on:
  workflow_dispatch:  # Enables manual trigger via GitHub UI

jobs:
  create-file:
    runs-on: ubuntu-latest  # Use a lightweight runner

    steps:
      - name: Set up SSH key for EC2 access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Create ok.txt file on EC2 if it doesn't exist
        run: |
          # SSH into the EC2 instance and check/create the ok.txt file
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} << 'EOF'
            TARGET_DIR="${{ secrets.TARGET_DIR }}"
            FILE_PATH="${TARGET_DIR}/ok.txt"

            # Check if ok.txt exists, and create it if it doesn't
            if [ ! -f "$FILE_PATH" ]; then
              touch "$FILE_PATH"
              echo "ok.txt file created at $FILE_PATH"
            else
              echo "ok.txt already exists at $FILE_PATH"
            fi
          EOF
