name: Setup Nginx with SSL and Reverse Proxy

on:
  workflow_dispatch: 

jobs:
  setup-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Nginx
        run: |
          # Update and install Nginx
          sudo apt update
          sudo apt install -y nginx openssl

          # Create a directory for SSL certificates
          sudo mkdir -p /etc/nginx/ssl

          # Generate a self-signed SSL certificate (adjust the domain for production)
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt -subj "/C=US/ST=State/L=City/O=Company/CN=${{ secrets.DOMAIN_NAME }}"

          # Configure Nginx to reverse proxy to port 3001 and use SSL
          sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80;
    server_name ${secrets.DOMAIN_NAME};

    # Redirect HTTP to HTTPS
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    server_name ${secrets.DOMAIN_NAME};

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    location / {
        proxy_pass http://localhost:3001;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF'

          # Test Nginx configuration
          sudo nginx -t

          # Restart Nginx to apply the changes
          sudo systemctl restart nginx

          # Allow Nginx traffic through the firewall (if applicable)
          sudo ufw allow 'Nginx Full'

      - name: Check Nginx status
        run: |
          sudo systemctl status nginx
