name: Deploy Nginx with SSL and Reverse Proxy to EC2

on:
  workflow_dispatch:

jobs:
  deploy-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key for EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Copy Python script to EC2
        run: |
          scp -i ec2_key.pem -o StrictHostKeyChecking=no create_nginx_config.py ubuntu@${{ secrets.HOST_DNS }}:/home/ubuntu/

      - name: Execute Python script to configure Nginx and SSL on EC2
        run: |
          ssh -i ec2_key.pem ubuntu@${{ secrets.HOST_DNS }} << 'EOF'
            set -e
            # Export DOMAIN_NAME and PORT as environment variables
            export DOMAIN_NAME="${{ secrets.DOMAIN_NAME }}"
            export PORT="${{ secrets.PORT }}"

            # Run the Python script with the domain and port as arguments
            python3 /home/ubuntu/create_nginx_config.py $DOMAIN_NAME $PORT
          EOF

      - name: Clean up SSH key
        run: |
          rm -f ec2_key.pem
