name: Deploy Nginx with SSL and Reverse Proxy to EC2

on:
  workflow_dispatch: 

jobs:
  deploy-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key for EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Copy Nginx setup script to EC2
        run: |
          scp -i ec2_key.pem setup_nginx.sh ${USERNAME}@${{ secrets.HOST_DNS }}:/home/${USERNAME}/setup_nginx.sh

      - name: SSH into EC2 and execute setup script
        run: |
          ssh -i ec2_key.pem ${USERNAME}@${{ secrets.HOST_DNS }} 'bash /home/${USERNAME}/setup_nginx.sh'

      - name: Clean up SSH key
        run: |
          rm -f ec2_key.pem
