name: Deploy Nginx with SSL and Reverse Proxy to EC2

on:
  workflow_dispatch:

jobs:
  deploy-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key for EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 400 ec2_key.pem

      - name: Copy Python script to EC2
        run: |
          scp -i ec2_key.pem create_nginx_config.py StrictHostKeyChecking=no ${USERNAME}@${{ secrets.HOST_DNS }}:/home/ubuntu/

      - name: Execute Python script to configure Nginx and SSL on EC2
        run: |
          ssh -i ec2_key.pem ubuntu@${{ secrets.HOST_DNS }} << 'EOF'
            python3 /home/ubuntu/create_nginx_config.py ${{ secrets.DOMAIN_NAME }} ${{ secrets.PORT }}
          EOF

      - name: Clean up SSH key
        run: |
          rm -f ec2_key.pem
